version: "3.8"

services:
  road-to-nowhere-web:
    depends_on:
      - road-to-nowhere-mysql
    container_name: road-to-nowhere-web
    build:
      context: .
      dockerfile: Dockerfile.road_to_nowhere_web
      args:
        - ROAD_TO_NOWHERE_PYTHON_VER
        - ROAD_TO_NOWHERE_PROJECT_DIR
    image: road-to-nowhere:1.0.0
    env_file: road_to_nowhere.env
    ports:
      - 5000:5000
    volumes:
      - $HOME/projects/road-to-nowhere:/usr/local/src/app
    entrypoint:
      - docker_configs/run.sh

  road-to-nowhere-mysql:
    container_name: road-to-nowhere-mysql
    image: mysql:5.7
    env_file: road_to_nowhere.env
    ports:
      - 3306:3306
    volumes:
      - road-to-nowehere-db:/var/lib/mysql

volumes:
  road-to-nowehere-db:
