service: road-to-nowhere

provider:
  name: aws
  region: us-east-2

resources:
  Resources:
    AuroraRDSCluster:
      Type: AWS::RDS::DBCluster
      Properties:
        DatabaseName: "Road to Nowhere Database"
        DBClusterIdentifier: road-to-nowhere-db
        Engine: aurora
        EngineMode: serverless
        EngineVersion: "5.6.10a"
        MasterUsername: ${ssm:/road-to-nowhere-username}
        MasterUserPassword: ${ssm:/road-to-nowhere-password}
        DBSubnetGroupName:
          Ref: "roadtonowhererdssubnetgroup"
        ScalingConfiguration:
          AutoPause: true
          MinCapacity: 1
          MaxCapacity: 64
          SecondsUntilAutoPause: 180
        BackupRetentionPeriod: 3
        EnableHttpEndpoint: false
        StorageEncrypted: true
        VpcSecurityGroupIds:
        - Ref: "RoadtoNowhereSecurityGroup"
        DeletionProtection: true
