"""Add bytes column types for password assc fields

Revision ID: 93dfd8a45d77
Revises: b2ce9d203246
Create Date: 2020-11-01 21:04:04.227202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93dfd8a45d77'
down_revision = 'b2ce9d203246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('api_token', table_name='user_model')
    op.drop_column('user_model', 'api_token')
    op.alter_column('user_model', 'password_hash', existing_type=sa.String(256), type_=sa.LargeBinary())
    op.alter_column('user_model', 'salt', existing_type=sa.String(256), type_=sa.LargeBinary())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('api_token', mysql.VARCHAR(length=256), nullable=True))
    op.create_index('api_token', 'user_model', ['api_token'], unique=True)
    op.alter_column('user_model', 'password_hash', existing_type=sa.LargeBinary(), type_=sa.String(256))
    op.alter_column('user_model', 'salt', existing_type=sa.LargeBinary(), type_=sa.String(256))
    # ### end Alembic commands ###
